AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TargetRegion:
    Type: String
    Default: ap-northeast-1

  BucketBaseName:
    Type: String
    Default: sagemaker-movie-recommender # SageMakerから利用するため、prefixをつけとく

  BucketSuffix:
    Type: String

  AccessIpAddress:
    Type: String

  VpcEndPoint:
    Type: String

Resources:
  BatchBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref BucketBaseName, !Ref BucketSuffix]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # バケットポリシーで、IPとVPCベースの制限を加える
  BatchBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BatchBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Effect: Allow
            Principal: "*"
            Resource: !Join ["", [!GetAtt BatchBucket.Arn, "/*"]]
            Condition:
              IpAddress:
                aws:SourceIp:
                  - !Ref AccessIpAddress
              StringEquals:
                aws:sourceVpc: !Ref VpcEndPoint

Outputs:
  BatchBucketName:
    Value: !Join
      - "-"
      - [!Ref BucketBaseName, !Ref BucketSuffix]
