apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-app
spec:
  schedule: "40 */1 * * *" # min hour day-of-month month day-of-week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-app
              image: ${ECR_HOST}/k8s-sample/batch-app:1.0.0
              imagePullPolicy: Always
          restartPolicy: OnFailure
