apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 935326844264.dkr.ecr.ap-northeast-1.amazonaws.com/k8s-sample/api
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          #   readinessProbe:
          #     httpGet:
          #       port: 80
          #       path: /ready
          #     initialDelaySeconds: 15
          #     periodSeconds: 30
          #   livenessProbe:
          #     httpGet:
          #       port: 80
          #       path: /health
          #     initialDelaySeconds: 30
          #     periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
